name: work_hu
description: See who's leading the local Work competition.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  cupertino_icons: ^1.0.2
  syncfusion_flutter_gauges: ^21.1.38
  dio: ^4.0.4
  overlay_support: ^2.0.0
  get: ^4.6.5
  auto_route: ^5.0.4
  get_it: ^7.2.0
  flutter_screenutil: ^5.9.0
  injectable: ^2.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  go_router: ^10.2.0
  flutter_web_frame: ^1.0.0
  flutter_secure_storage: ^6.0.0
  crypto: ^3.0.1
  bcrypt: ^1.1.3
  pointycastle: ^3.1.1
  intl: ^0.18.1
  dropdown_search: ^5.0.6
  excel: ^4.0.2
  file_picker: ^6.0.0
  csv: ^5.1.0
  file_saver: ^0.2.8
  drop_down_search_field: ^1.0.3
  flutter_localizations:
    sdk: flutter
  localization: ^2.1.1
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mocktail: ^0.3.0
  auto_route_generator:
  injectable_generator:
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/img/
    - assets/logos/
    - assets/icons/
    - assets/docs/
    - lib/
    - lib/I18n/

#  generate: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 800
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          style: italic
