name: work_hu
description: See the status of the competition. Follow your MyShare status and much more.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  cupertino_icons: ^1.0.2
  syncfusion_flutter_gauges: ^25.1.35
  dio: ^5.4.1
  overlay_support: ^2.0.0
  get: ^4.6.5
  auto_route: ^7.9.2
  get_it: ^7.2.0
  flutter_screenutil: ^5.9.0
  injectable: ^2.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  go_router: ^13.2.1
  flutter_web_frame: ^1.0.0
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.1
  bcrypt: ^1.1.3
  pointycastle: ^3.1.1
  intl: ^0.19.0
  excel: ^4.0.2
  file_picker: ^8.0.0+1
  csv: ^6.0.0
  file_saver: ^0.2.8
  drop_down_search_field: ^1.0.4
  flutter_localizations:
    sdk: flutter
  localization: ^2.1.1
  http_parser: ^4.0.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.3.3
  mocktail: ^1.0.3
  auto_route_generator:
  injectable_generator: ^2.6.1
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/img/
    - assets/logos/
    - assets/icons/
    - assets/docs/
    - lib/
    - lib/I18n/

#  generate: true

  fonts:
    - family: Good-Timing
      fonts:
        - asset: assets/fonts/Good-Timing-Light.ttf
        - asset: assets/fonts/Good-Timing-Bold.otf
          weight: 800
